services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'nestjs_typeorm'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'